---
title: "Arrange individual figures into a collage"
author: "Christian Holland"
date: "6/23/2019"
output: html_document
---

```{r "knitr config", cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::knit(..., quiet = TRUE)
```
### Libraries and sources
These libraries and sources are used in this analysis 
```{r "setup", message=F}
library(tidyverse)
library(cowplot)
library(tidylog)
library(grid)
library(gridExtra)

options("tidylog.display" = list(print))
theme_set(theme_cowplot())
```
### CCL4 experiment
#### CCl4 - Main1
```{r}
ccl4_path = "fig/ccl4_experiment/"
design = ggdraw() +
  draw_image(str_c(ccl4_path, "experimental_design.jpg"))
pca_all = readRDS(str_c(ccl4_path, "pca_all_text.rds"))
volcano = readRDS(str_c(ccl4_path, "volcano_plot_ccl4.rds"))
top_ccl4_deg = readRDS(str_c(ccl4_path, "top_ccl4_degs.rds"))
progeny = readRDS(str_c(ccl4_path, "progeny_ccl4.rds"))
dorothea = readRDS(str_c(ccl4_path, "dorothea_ccl4.rds"))
go_ccl4 = readRDS(str_c(ccl4_path, "go_ccl4.rds"))

top_ccl4_deg_collage = plot_grid(
  plot_grid(
    top_ccl4_deg$up_8 + theme(plot.margin = margin(0,-0.1,0,0, "cm")), 
    top_ccl4_deg$down_8 + theme(plot.margin = margin(0,0,0,-0.1, "cm")),
    align = "h", axis = "tb"
    ) %>%
  gridExtra::grid.arrange(top = textGrob("Month 2", 
                                         gp=gpar(fontsize=12))),
  NULL,
  plot_grid(
    top_ccl4_deg$up_24 + theme(plot.margin = margin(0,-0.1,0,0, "cm")), 
    top_ccl4_deg$down_24 + theme(plot.margin = margin(0,0,0,-0.1, "cm")),
    align = "h", axis = "tb"
    ) %>%
  gridExtra::grid.arrange(top = textGrob("Month 6", 
                                         gp=gpar(fontsize=12))),
  NULL,
  plot_grid(
    top_ccl4_deg$up_48 + theme(plot.margin = margin(0,-0.1,0,0, "cm")), 
    top_ccl4_deg$down_48 + theme(plot.margin = margin(0,0,0,-0.1, "cm")),
    align = "h", axis = "tb", rel_widths = c(1.3,1)
    ) %>%
  gridExtra::grid.arrange(top = textGrob("Month 12", 
                                         gp=gpar(fontsize=12))),
  ncol=5, rel_widths = c(1, 0.1, 1, 0.1, 1)
)

up = plot_grid(
  design, pca_all,
  ncol=2, labels = c("A.", "B."), label_size = 18
)

mid = plot_grid(
  volcano, progeny, dorothea,
  rel_widths = c(1,0.4,0.4),
  ncol=3, labels = c("C.", "E.", "F."), label_size = 18
)


bottom = plot_grid(
  top_ccl4_deg_collage, go_ccl4,
  rel_widths = c(1,0.8),
  ncol=2, labels = c("D.", "G."), label_size = 18
)

ccl4_experiment_main1 = plot_grid(
  up,
  mid,
  bottom,
  ncol=1
)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/Figure 2.pdf",
  ccl4_experiment_main1,
  width=15, height=18)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/Figure 2.tiff",
  ccl4_experiment_main1,
  width=15, height=18)

ggsave("paper/figures/ccl4_experiment_main1.pdf",
       ccl4_experiment_main1,
       width = 15, height = 18)
```

#### Oil - Supp1
```{r}
ccl4_path = "fig/ccl4_experiment/"
volcano = readRDS(str_c(ccl4_path, "volcano_plot_oil.rds"))
top_oil_deg = readRDS(str_c(ccl4_path, "top_oil_degs.rds"))


top_oil_deg_collage = plot_grid(
  plot_grid(
    top_oil_deg$up_8 + theme(plot.margin = margin(0,-0.1,0,0, "cm")), 
    top_oil_deg$down_8 + theme(plot.margin = margin(0,0,0,-0.1, "cm")),
    align = "h", axis = "tb", rel_widths = c(0.75,1)
    ) %>%
  gridExtra::grid.arrange(top = textGrob("Month 2", 
                                         gp=gpar(fontsize=12))),
  plot_grid(
    top_oil_deg$up_48 + theme(plot.margin = margin(0,-0.1,0,0, "cm")), 
    top_oil_deg$down_48 + theme(plot.margin = margin(0,0,0,-0.1, "cm")),
    align = "h", axis = "tb", rel_widths = c(0.75,1)
    ) %>%
  gridExtra::grid.arrange(top = textGrob("Month 12", 
                                         gp=gpar(fontsize=12))),
  ncol=2
)


ccl4_experiment_supp = plot_grid(
  volcano,
  top_oil_deg_collage, ncol=1, labels = c("A.", "B."), label_size = 18
)


ggsave("paper/figures/ccl4_experiment_supp.pdf", 
       ccl4_experiment_supp,
       width = 10, height = 10)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/SFigure Y.tiff",
  ccl4_experiment_supp,
  width=10, height=10)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/SFigure Y.pdf",
  ccl4_experiment_supp,
  width=10, height=10)
```

### Zonation
#### Main
```{r "in silico benchmark - main"}
consensus_gsea_ccl4_bar = readRDS("fig/zonation/consensus_pc_pp_gsea_ccl4.rds")
gsea_plots_ccl4_df = readRDS("fig/zonation/gsea_plots_ccl4.rds")
leading_edge_hmap = readRDS("fig/zonation/leading_edge_hmap.rds")
ora_tab = readRDS("fig/zonation/tab.rds")

gsea_plots_ccl4 = plot_grid(plotlist = gsea_plots_ccl4_df$gsea_plots, ncol=2)
right = plot_grid(
  consensus_gsea_ccl4_bar, leading_edge_hmap, ora_tab,
  ncol=1, labels = c("B.", "C.", "D."), label_size = 18
)

zonation_main = plot_grid(
  gsea_plots_ccl4, right, ncol=2,rel_widths = c(1.25,1), labels = c("A.", NULL), label_size = 18
)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/Figure 3.pdf",
  zonation_main,
  width=15, height=18)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/Figure 3.tiff",
  zonation_main,
  width=15, height=18)

ggsave("paper/figures/zonation_main.pdf",
       zonation_main, width = 15, height = 18)
```

#### Supp1
```{r}
pc_venn = readRDS("fig/zonation/pc_venn.rds")
pp_venn = readRDS("fig/zonation/pp_venn.rds")

zonation_supp1 = plot_grid(
 pc_venn, NULL, pp_venn, 
 rel_widths = c(1,0.1,1), ncol=3
)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/SFigure X.pdf",
  zonation_supp1,
  width=10, height=5)

ggsave(
  "~/Google Drive/Paper/LiverPeriportalization/Cells/Figures/SFigure X.tiff",
  zonation_supp1,
  width=10, height=5)

ggsave("paper/figures/zonation_supp1.pdf", 
       zonation_supp1,
       width = 10, height = 5)
```